config/routes.rb
Rails.application.routes.draw do
  root "companions#index"
  resources :companions do
    resources :posts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/companion.rb
class Companion < ApplicationRecord
    has_many :posts, dependent: :destroy
    validates :name, presence: true, uniqueness: true, length: { minimum: 3}
    validates :age, presence: true, numericality: { greater_than:18 }
    validates_presence_of :height, :bio
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :companion
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companions_controller.rb
class CompanionsController < ApplicationController
  before_action :set_companion, only: %i[ show edit update destroy ]

  # GET /companions or /companions.json
  def index
    @companions = Companion.all
  end

  # GET /companions/1 or /companions/1.json
  def show
  end

  # GET /companions/new
  def new
    @companion = Companion.new
  end

  # GET /companions/1/edit
  def edit
  end

  # POST /companions or /companions.json
  def create
    @companion = Companion.new(companion_params)

    respond_to do |format|
      if @companion.save
        format.html { redirect_to companion_url(@companion), notice: "Companion was successfully created." }
        format.json { render :show, status: :created, location: @companion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @companion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companions/1 or /companions/1.json
  def update
    respond_to do |format|
      if @companion.update(companion_params)
        format.html { redirect_to companion_url(@companion), notice: "Companion was successfully updated." }
        format.json { render :show, status: :ok, location: @companion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @companion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companions/1 or /companions/1.json
  def destroy
    @companion.destroy

    respond_to do |format|
      format.html { redirect_to companions_url, notice: "Companion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_companion
      @companion = Companion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def companion_params
      params.require(:companion).permit(:name, :age, :height, :bio)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def create
        @companion =Companion.find(params[:companion_id])
        @post = @companion.posts.new(post_params)

        respond_to do |format|
            if @post.save
              format.html { redirect_to companion_posts_url(@companion), notice: "Post was successfully created." }
              format.json { render :show, status: :created, location: @companion }
            else
              format.html { render :companion/posts, status: :unprocessable_entity }
              format.json { render json: @post.errors, status: :unprocessable_entity }
            end
          end


    end

    def destroy
        @post= @companion.posts.find(params[:id])
        @post.destroy
    end


    private

    def post_params
        params.require(:companion).permit(:body, :companion_id)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companions_helper.rb
module CompanionsHelper
end

app/views/companions/_allposts.html.erb
<% for post in @companion.posts %>
    <%= post.body%>
<% end %>

app/views/companions/_companion.html.erb
<div id="<%= dom_id companion %>">
  <p>
    <strong>Name:</strong>
    <%= companion.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= companion.age %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= companion.height %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= companion.bio %>
  </p>

</div>

app/views/companions/_form.html.erb
<%= form_with(model: companion) do |form| %>
  <% if companion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(companion.errors.count, "error") %> prohibited this companion from being saved:</h2>

      <ul>
        <% companion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/companions/_posts.html.erb
<%= form_with(model: [@companion, @companion.posts.build]) do |form| %>
    <%= form.text_area :body, placeholder: "Your post here" %>
    <br>
    <%= form.submit %>

<% end %>

app/views/companions/edit.html.erb
<h1>Editing companion</h1>

<%= render "form", companion: @companion %>

<br>

<div>
  <%= link_to "Show this companion", @companion %> |
  <%= link_to "Back to companions", companions_path %>
</div>

app/views/companions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Companions</h1>

<div id="companions">
  <% @companions.each do |companion| %>
    <%= render companion %>
    <p>
      <%= link_to "Show this companion", companion %>
    </p>
  <% end %>
</div>

<%= link_to "New companion", new_companion_path %>

app/views/companions/new.html.erb
<h1>New companion</h1>

<%= render "form", companion: @companion %>

<br>

<div>
  <%= link_to "Back to companions", companions_path %>
</div>

app/views/companions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @companion %>

<div>
  <%= link_to "Edit this companion", edit_companion_path(@companion) %> |
  <%= link_to "Back to companions", companions_path %>

  <%= button_to "Destroy this companion", @companion, method: :delete %>
</div>

<div>
  <h2>Posts </h2>

  <%= form_with(model: [@companion, @companion.posts.build]) do |form| %>
      <%= form.text_area :body, placeholder: "Your post here" %>
      <br>
      <%= form.submit %>
  <% end %>

</div>

<div>
  <%= render 'companions/allposts'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matchapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>